apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuick-role
  namespace: default
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: kuick
    namespace: default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kuick-role
