apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuick-role
  namespace: default
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list"]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins"]
    verbs: ["list"]
